### ISSUE TITLE
Build failed : solution (temporary)

### ISSUE THREAD

**Issue by Productivix** [rozele/react-native-activity-results#7]
on RN 0.70.5, 
I install this package with only : 
yarn add react-native-activity-result

and I had a FAILURE: Build failed with an exception.
the **solution** is to replace in the module the joined  android> build.gradle file
[build.zip](https://github.com/rozele/react-native-activity-result/files/9969215/build.zip)
- should be a PR

**Comment by neemiasbj** [comment]
Hi, my app closes when the activity is finished, it don't come back to my app, any ideas?

**Comment by Productivix** [comment]
hi : does not seem to be maintained any more !
